// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEM_uAi7GFhMPqVcwtIsyZmbDQL7TrM2A',
    appId: '1:118109513018:web:a7088c3c632d1488e81c03',
    messagingSenderId: '118109513018',
    projectId: 'tradeguardpro5',
    authDomain: 'tradeguardpro.one-terminal.com',
    storageBucket: 'tradeguardpro5.firebasestorage.app',
    measurementId: 'G-7EQR9SBX2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbbTXgGyylP3BikBZl1SWgaevvkhQuQc',
    appId: '1:118109513018:android:a37cef40e4e861c3e81c03',
    messagingSenderId: '118109513018',
    projectId: 'tradeguardpro5',
    storageBucket: 'tradeguardpro5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEM_uAi7GFhMPqVcwtIsyZmbDQL7TrM2A',
    appId: '1:118109513018:web:33dd2e87e2a4d753e81c03',
    messagingSenderId: '118109513018',
    projectId: 'tradeguardpro5',
    authDomain: 'tradeguardpro.one-terminal.com',
    storageBucket: 'tradeguardpro5.firebasestorage.app',
    measurementId: 'G-6S75R5JVE4',
  );

}